name: gs-price-service
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gs-price-service-db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'
